spring:
  application:
    name: library-management-system

  datasource:
    url: jdbc:postgresql://localhost:5432/lab_db
    username: lab_user
    password: lab_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  logging:
    level:
      # Отключаем DEBUG логи Hibernate
      org.hibernate: WARN
      org.hibernate.SQL: WARN
      org.hibernate.type.descriptor.sql: WARN
      org.hibernate.stat: WARN
      # Spring логирование
      org.springframework: INFO
      org.springframework.transaction: WARN
      org.springframework.orm: WARN
      # Наш проект
      edu.sfu: INFO

    pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
    show-sql: false

  jackson:
    serialization:
      indent-output: true

server:
  port: 8080
  servlet:
    context-path: /api